artists = [
    "Green Crow",
    "Gorillaz",
    "Frank Sinatra",
    "Europe",
    "Ed Sheeran",
    "Eagles",
    "Brainstorm",
    "Linkin Park",
    "Lionel Richie",
    "Lumen",
    "Noize Mc",
    "Pixies",
    "RHCP",
    "Rick Astley",
    "Scorpions",
    "Simon & Garfunkel",
    "Styx - Boat on the river",
    "Sunrise Avenue - Fairytale gone bad",
    "The Dartz",
    "The Pretty Reckless",
    "Tones And I - Dance Monkey",
    "Wallace Band",
    "5'nizza",
    "7Б",
    "Агата Кристи",
    "Альянс",
    "Ария",
    "Аукцион",
    "Би-2",
    "Город 312",
    "Дайте Танк",
    "ДДТ",
    "Кино",
    "Король и Шут",
    "Крематорий",
    "Кукрыниксы",
    "МакSим",
    "Мельница",
    "Монеточка",
    "Мумий Тролль",
    "Мураками - Нулевой Километр",
    "Наутилус Помпилиус",
    "Нежность на Бумаге",
    "Несчастный случай",
    "Ногу Свело",
    "Ночные снайперы",
    "Океан Эльзи - Без бою",
    "Отпетые Мошенники - Люби меня люби",
    "Пикник",
    "Пилот",
    "Порнофильмы",
    "Ранетки",
    "Секрет",
    "Сердце Дурака",
    "Серебряная свадьба",
    "Смысловые галлюцинации",
    "Сплин",
    "Гарик Сукачёв",
    "Танцы минус",
    "Тату",
    "Ундервуд",
    "Чайф",
    "Чиж&Ко",
    "Екатерина Яшникова",
    "A-Ha - Take on Me",
    "Adele - Rolling in the deep",
    "Alex Clare - Too Close",
    "Amy Winehouse",
    "Animal Jazz",
    "Ariana Grande - Love the way  you lie",
    "Beatles",
    "Billy's Band",
    "Bob Dylan",
    "38 Попугаев - Ром, плеть содомия",
    "Юлия Савичева - Если в сердце живёт любовь",
    "Тол Мириам",
    "Гражданская оборона",
    "По выбору зрителей",
    "По выбору гитариста"
]
