artists = [
    "Green Crow",
    "Gorillaz",
    "Frank Sinatra",
    "Europe",
    "Ed Sheeran",
    "Eagles",
    "Brainstorm",
    "Linkin Park",
    "Lionel Richie",
    "Lumen",
    "Noize Mc",
    "Pixies",
    "RHCP",
    "Rick Astley",
    "Scorpions",
    "Simon & Garfunkel",
    "Styx",
    "Sunrise Avenue",
    "The Dartz",
    "The Pretty Reckless",
    "Tones And I",
    "Wallace Band",
    "5'nizza",
    "7Б",
    "Агата Кристи",
    "Альянс",
    "Ария",
    "Аукцион",
    "Би-2",
    "Город 312",
    "Дайте Танк",
    "ДДТ",
    "Кино",
    "Король и Шут",
    "Крематорий",
    "Кукрыниксы",
    "МакSим",
    "Мельница",
    "Монеточка",
    "Мумий Тролль",
    "Мураками",
    "Наутилус Помпилиус",
    "Нежность на Бумаге",
    "Несчастный случай",
    "Ногу Свело",
    "Ночные снайперы",
    "Океан Эльзи",
    "Отпетые Мошенники",
    "Пикник",
    "Пилот",
    "Порнофильмы",
    "Ранетки",
    "Секрет",
    "Сердце Дурака",
    "Серебряная свадьба",
    "Смысловые галлюцинации",
    "Сплин",
    "Гарик Сукачёв",
    "Танцы минус",
    "Тату",
    "Ундервуд",
    "Чайф",
    "Чиж&Ко",
    "Екатерина Яшникова",
    "A-Ha",
    "Adele",
    "Alex Clare",
    "Amy Winehouse",
    "Animal Jazz",
    "Ariana Grande",
    "Beatles",
    "Billy's Band",
    "Bob Dylan"

]
